### ISSUE TITLE
define cxinc for 5.8 and 5.10

### ISSUE THREAD

**Issue by y** [Dual-Life/Devel-PPPort#26]
http://www.nntp.perl.org/group/perl.perl5.porters/2009/07/msg149207.html

    # if PERL_VERSION < 12
    # define cxinc()                        Perl_cxinc(aTHX)
    # endif

**Comment by khwilliamson** [comment]
Is this still needed?  Is there a reason not to apply it?

**Comment by khwilliamson** [comment]
Running
perl ppport.h --api-info=/cxinc/ 
yields
=== cxinc ===

Supported at least since perl-5.003_07, with or without ppport.h.

Since this is undocumented, the API should be considered unstable.
It may be that this is not intended for XS use, or it may just be
that no one has gotten around to documenting it.
Send email to perl5-porters@perl.org if you need to have this functionality.
========
That wouldn't happen if cxinc were undefined in 5.8 and 5.10.  So I don't know what the original motivation of this ticket was.  Since the OP has not responded in 8 months, and it appears that there isn't a bug here, I'm closing this ticket, which of course can be reopened if necessary.
No response from in 8 months.
