### ISSUE TITLE
Run make regen after regenerating Makefile

### ISSUE THREAD

**Issue by atoomic** [Dual-Life/Devel-PPPort#76]
from Perl RT 134114
author: Pali
URL: https://rt.perl.org/Ticket/Display.html?id=134114

> This would ensure that all auto-generated files are up-to-date after running configure phase.

**Comment by karenetheridge** [comment]
Isn't this confusing the 'configure' and 'build' phases? `perl Makefile.PL` should not be invoking `make`.

**Comment by pali** [comment]
Maybe slightly yes. But because autogenerated files (which should be part of build) are included in git repository, the best match for updating them is configure phase.

Other option would be to completelty delete those autogenerated files from git and generate them in build phase. But HACKING file says that it is problematic.

**Comment by atoomic** [comment]
I think adding the `regen_tests` is probably what we try to do there and we should plug it somewhere else as dependency? maybe `make dist`? or trigger it if `AUTHOR_TESTING` is set?

**Comment by atoomic** [comment]
what about adding `regen_test` as dependency to the target `test`?

**Comment by pali** [comment]
It is not only tests what is generated. Also whole ppport is generated by make regen.

**Comment by atoomic** [comment]
correct but make `all` generate all these files already? so I think test is the only issue

**Comment by atoomic** [comment]
but I agree with you @pali  we can probably simply add `regen` as dep to `test` it will not hurt

**Comment by pali** [comment]
regen should not be Makefile's dependency for test. You do not want to regenerate all files every time when running 'make test'. Because when you regenerate files, it means whole ppport needs to be-recompiled (timestamps of generated files is newer then last time compiled binaries). Also if you do it, you just slow down 'make test' run.

**Comment by atoomic** [comment]
you are right... what do you think about `regen_test` as dependency to the `test` target

**Comment by pali** [comment]
Still, it should not be dependency which is run unconditionally. But rather some "correct" Makefile dependency, that test t/abc.t depends on file from which it is generated...

**Comment by pali** [comment]
@atoomic In https://github.com/Dual-Life/Devel-PPPort/issues/76#issuecomment-493502156 is missing inter-dependency between RealPPPort.xs, PPPort.pm and ppport.h. RealPPPort.xs depends on ppport.h and ppport.h depends on PPPort.pm. Without correct dependences between them running `make all` would generate those files in random order.

I tried to fix these problems in pull request https://github.com/Dual-Life/Devel-PPPort/pull/83 but do not know if it catch all corner cases.

Calling `make regen` directly from Makefile.PL is the safest option.

**Comment by pali** [comment]
So I would suggest to apply **both** changes. From this ticket and also from #83.

**Comment by atoomic** [comment]
As mentionned in https://github.com/Dual-Life/Devel-PPPort/pull/77
this is now fixed with  #83 and https://github.com/Dual-Life/Devel-PPPort/pull/95

We can close this case
